version: "3.8"

services:
  wiremock:
    image: wiremock/wiremock:3.5.2
    ports:
      - "9090:8080"
    volumes:
      - ./docker/wiremock/mappings:/home/wiremock/mappings
      - ./docker/wiremock/__files:/home/wiremock/__files
    command: ["--verbose"]
